// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[LPAREN-1]
	_ = x[RPAREN-2]
	_ = x[LBRACE-3]
	_ = x[RBRACE-4]
	_ = x[LSQR-5]
	_ = x[RSQR-6]
	_ = x[COMMA-7]
	_ = x[DOT-8]
	_ = x[SEMICOLON-9]
	_ = x[BANG-10]
	_ = x[NEQ-11]
	_ = x[EQ-12]
	_ = x[EQ_EQ-13]
	_ = x[GT-14]
	_ = x[GT_EQ-15]
	_ = x[LT-16]
	_ = x[LT_EQ-17]
	_ = x[PLUS-18]
	_ = x[PLUS_EQ-19]
	_ = x[MINUS-20]
	_ = x[MINUS_EQ-21]
	_ = x[SLASH-22]
	_ = x[SLASH_EQ-23]
	_ = x[STAR-24]
	_ = x[STAR_EQ-25]
	_ = x[PERCENT-26]
	_ = x[PERCENT_EQ-27]
	_ = x[IDENTIFIER-28]
	_ = x[STRING-29]
	_ = x[NUMBER-30]
	_ = x[AND-31]
	_ = x[CLASS-32]
	_ = x[ELSE-33]
	_ = x[FALSE-34]
	_ = x[FUN-35]
	_ = x[FOR-36]
	_ = x[IF-37]
	_ = x[NIL-38]
	_ = x[OR-39]
	_ = x[STATIC-40]
	_ = x[PRINT-41]
	_ = x[RETURN-42]
	_ = x[SUPER-43]
	_ = x[THIS-44]
	_ = x[TRUE-45]
	_ = x[VAR-46]
	_ = x[WHILE-47]
	_ = x[BREAK-48]
	_ = x[EOF-49]
}

const _TokenType_name = "NONELPARENRPARENLBRACERBRACELSQRRSQRCOMMADOTSEMICOLONBANGNEQEQEQ_EQGTGT_EQLTLT_EQPLUSPLUS_EQMINUSMINUS_EQSLASHSLASH_EQSTARSTAR_EQPERCENTPERCENT_EQIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORSTATICPRINTRETURNSUPERTHISTRUEVARWHILEBREAKEOF"

var _TokenType_index = [...]uint8{0, 4, 10, 16, 22, 28, 32, 36, 41, 44, 53, 57, 60, 62, 67, 69, 74, 76, 81, 85, 92, 97, 105, 110, 118, 122, 129, 136, 146, 156, 162, 168, 171, 176, 180, 185, 188, 191, 193, 196, 198, 204, 209, 215, 220, 224, 228, 231, 236, 241, 244}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
