// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[SEMICOLON-7]
	_ = x[BANG-8]
	_ = x[BANG_EQUAL-9]
	_ = x[EQUAL-10]
	_ = x[EQUAL_EQUAL-11]
	_ = x[GREATER-12]
	_ = x[GREATER_EQUAL-13]
	_ = x[LESS-14]
	_ = x[LESS_EQUAL-15]
	_ = x[PLUS-16]
	_ = x[PLUS_EQUAL-17]
	_ = x[MINUS-18]
	_ = x[MINUS_EQUAL-19]
	_ = x[SLASH-20]
	_ = x[SLASH_EQUAL-21]
	_ = x[STAR-22]
	_ = x[STAR_EQUAL-23]
	_ = x[IDENTIFIER-24]
	_ = x[STRING-25]
	_ = x[NUMBER-26]
	_ = x[AND-27]
	_ = x[CLASS-28]
	_ = x[ELSE-29]
	_ = x[FALSE-30]
	_ = x[FUN-31]
	_ = x[FOR-32]
	_ = x[IF-33]
	_ = x[NIL-34]
	_ = x[OR-35]
	_ = x[STATIC-36]
	_ = x[PRINT-37]
	_ = x[RETURN-38]
	_ = x[SUPER-39]
	_ = x[THIS-40]
	_ = x[TRUE-41]
	_ = x[VAR-42]
	_ = x[WHILE-43]
	_ = x[BREAK-44]
	_ = x[EOF-45]
}

const _TokenType_name = "NONELEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTSEMICOLONBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALPLUSPLUS_EQUALMINUSMINUS_EQUALSLASHSLASH_EQUALSTARSTAR_EQUALIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORSTATICPRINTRETURNSUPERTHISTRUEVARWHILEBREAKEOF"

var _TokenType_index = [...]uint16{0, 4, 14, 25, 35, 46, 51, 54, 63, 67, 77, 82, 93, 100, 113, 117, 127, 131, 141, 146, 157, 162, 173, 177, 187, 197, 203, 209, 212, 217, 221, 226, 229, 232, 234, 237, 239, 245, 250, 256, 261, 265, 269, 272, 277, 282, 285}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
